'''
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

4613732
'''


list = [1, 1]
fibo = 0
while fibo < 4000000:
    fibo = int(list[-1]) + int(list[-2])
    list.append(fibo)
    print(fibo)
sum = 0
for i in range(int(len(list))):
    if list[i] % 2 == 0:
        sum = sum + list[i]
    else:
        continue
print(sum)